/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupSlugRouteImport } from './routes/$startupSlug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as Cohort3RouteImport } from './routes/cohort-3'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as StartupsRouteImport } from './routes/startups'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupSlugRoute = StartupSlugRouteImport.update({
  id: '/$startupSlug',
  path: '/$startupSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Cohort3Route = Cohort3RouteImport.update({
  id: '/cohort-3',
  path: '/cohort-3',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$startupSlug': typeof StartupSlugRoute
  '/admin': typeof AdminRoute
  '/cohort-3': typeof Cohort3Route
  '/investor': typeof InvestorRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/startups': typeof StartupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$startupSlug': typeof StartupSlugRoute
  '/admin': typeof AdminRoute
  '/cohort-3': typeof Cohort3Route
  '/investor': typeof InvestorRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/startups': typeof StartupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$startupSlug': typeof StartupSlugRoute
  '/admin': typeof AdminRoute
  '/cohort-3': typeof Cohort3Route
  '/investor': typeof InvestorRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/startups': typeof StartupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$startupSlug'
    | '/admin'
    | '/cohort-3'
    | '/investor'
    | '/jobs'
    | '/login'
    | '/portal'
    | '/startups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$startupSlug'
    | '/admin'
    | '/cohort-3'
    | '/investor'
    | '/jobs'
    | '/login'
    | '/portal'
    | '/startups'
  id:
    | '__root__'
    | '/'
    | '/$startupSlug'
    | '/admin'
    | '/cohort-3'
    | '/investor'
    | '/jobs'
    | '/login'
    | '/portal'
    | '/startups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StartupSlugRoute: typeof StartupSlugRoute
  AdminRoute: typeof AdminRoute
  Cohort3Route: typeof Cohort3Route
  InvestorRoute: typeof InvestorRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  StartupsRoute: typeof StartupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$startupSlug': {
      id: '/$startupSlug'
      path: '/$startupSlug'
      fullPath: '/$startupSlug'
      preLoaderRoute: typeof StartupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort-3': {
      id: '/cohort-3'
      path: '/cohort-3'
      fullPath: '/cohort-3'
      preLoaderRoute: typeof Cohort3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StartupSlugRoute: StartupSlugRoute,
  AdminRoute: AdminRoute,
  Cohort3Route: Cohort3Route,
  InvestorRoute: InvestorRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  StartupsRoute: StartupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
